"""The confidentiality check must actually detect something.

A check that has never failed is a check nobody has tested — so this plants a
term and asserts the scanner finds it.

Note what this file does NOT contain: any real forbidden term. It generates its
own sentinel and its own hash file (via FORBIDDEN_HASHES) to exercise the
mechanism. Writing the real terms here would reintroduce exactly the leak the
scanner exists to prevent — which is a mistake I made once already while writing
this test.
"""

from __future__ import annotations

import hashlib
import os
import re
import subprocess
import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
SCRIPT = BACKEND / "etl" / "check_no_vendor_terms.py"
HASHES = BACKEND / "etl" / "forbidden_hashes.txt"

SENTINEL = "qqzsentinelterm"


def _run(target: Path, hashes: Path | None = None) -> subprocess.CompletedProcess:
    env = dict(os.environ)
    if hashes is not None:
        env["FORBIDDEN_HASHES"] = str(hashes)
    return subprocess.run(
        [sys.executable, str(SCRIPT), str(target)],
        capture_output=True,
        text=True,
        check=False,
        env=env,
    )


def _digests() -> list[str]:
    return [
        line.split("#")[0].strip()
        for line in HASHES.read_text().splitlines()
        if line.split("#")[0].strip()
    ]


def test_committed_hash_file_is_populated_and_is_all_hashes():
    digests = _digests()
    assert len(digests) >= 3
    for d in digests:
        assert len(d) == 64 and re.fullmatch(r"[0-9a-f]{64}", d), d


def test_committed_hash_file_holds_no_plaintext_word():
    """The check must not publish what it checks for."""
    prose = {
        "sha", "forbidden", "vendor", "identifiers", "lowercased", "hashed",
        "deliberately", "plaintext", "denylist", "public", "repository",
        "publishes", "very", "name", "exists", "exclude", "check", "terms",
        "newterm", "sha256sum", "printf", "add", "term", "the", "that", "see",
        "etl", "no", "code", "sum",
    }
    for token in re.findall(r"[a-z]{3,}", HASHES.read_text().lower()):
        if re.fullmatch(r"[a-f]+", token):
            continue  # a fragment of a hex digest
        assert token in prose, f"possible plaintext term in the hash file: {token!r}"


def test_detects_a_planted_term_case_insensitively(tmp_path):
    hashes = tmp_path / "hashes.txt"
    hashes.write_text(
        "# generated by the test suite\n"
        + hashlib.sha256(SENTINEL.encode()).hexdigest()
        + "\n"
    )
    tree = tmp_path / "tree"
    (tree / "sub").mkdir(parents=True)
    (tree / "sub" / "leak.md").write_text(f"mentions {SENTINEL.upper()} here\n")
    (tree / "clean.md").write_text("nothing to see\n")

    result = _run(tree, hashes)
    assert result.returncode == 1, result.stdout
    assert "sub/leak.md:1" in result.stdout
    # The report gives a location and never echoes the matched token.
    assert SENTINEL not in result.stdout.lower()


def test_passes_on_a_clean_tree(tmp_path):
    hashes = tmp_path / "hashes.txt"
    hashes.write_text(hashlib.sha256(SENTINEL.encode()).hexdigest() + "\n")
    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "clean.md").write_text("ordinary text about doctors and visits\n")

    result = _run(tree, hashes)
    assert result.returncode == 0, result.stdout
    assert "PASS" in result.stdout


def test_skips_binary_and_vendor_directories(tmp_path):
    hashes = tmp_path / "hashes.txt"
    hashes.write_text(hashlib.sha256(SENTINEL.encode()).hexdigest() + "\n")
    tree = tmp_path / "tree"
    (tree / "node_modules").mkdir(parents=True)
    (tree / "node_modules" / "dep.js").write_text(f"var x = '{SENTINEL}'\n")
    (tree / "data.parquet").write_bytes(SENTINEL.encode())
    # One real file so the tree is not *entirely* skipped. Without it this test
    # asserted exit 0 over a zero-file scan, which would also have passed if the
    # scanner had walked nothing at all — the same vacuous pass the scanner now
    # rejects outright.
    (tree / "readme.md").write_text("ordinary text\n")

    result = _run(tree, hashes)
    assert result.returncode == 0, result.stdout
    assert "scanned 1 text file" in result.stdout
